POST http://localhost:5000/articles/new
Content-Type: application/json

{
     "title": "test titre",
    "author": "test auteur",
    "text": "test",
    "category_id": "60efd83652f56cfc2cfae530",
    "slug":"test titre"  
}